### ISSUE TITLE
Simple-JSON for #5?

### ISSUE THREAD

**Issue by justinwoo** [reaktor/purescript-workshop#1]
Instead of using Foreign-Generics, people could use newtype derived instances for Records from Simple-JSON. https://github.com/reaktor/purescript-workshop/tree/master/exercise5

Should this be added to the README of the exercise or replace the hint or something?

**Comment by hoodunit** [comment]
Yeah, this might be a good idea. A few things would need to be re-worked, though, as right now it introduces Generic type classes in the previous exercise and this is an extension of that.

**Comment by hoodunit** [comment]
I switched it to Simple.JSON in the process of trimming various topics.
